# Generated by Django 5.0.14 on 2026-02-08 11:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the group (e.g., 'Group 1', 'Downtown Group').", max_length=100)),
                ('overseers', models.ManyToManyField(blank=True, help_text='Users who have admin access to this group.', related_name='managed_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('baptism_date', models.DateField(blank=True, null=True)),
                ('is_regular_pioneer', models.BooleanField(default=False, help_text='Check if the publisher is a Regular Pioneer.')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for generating public access links.', unique=True)),
                ('active', models.BooleanField(default=True, help_text='Uncheck if publisher moves or becomes inactive.')),
                ('group', models.ForeignKey(help_text='The group this publisher belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='publishers', to='organization.group')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
