# Generated by Django 5.0.14 on 2026-02-08 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Congregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='congregation',
            field=models.ForeignKey(help_text='The congregation this group belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='organization.congregation'),
        ),
    ]
