# Generated by Django 5.0.14 on 2026-02-08 14:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_congregation_group_congregation'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='invitation_active',
            field=models.BooleanField(default=True, help_text='If Invite Link is active.'),
        ),
        migrations.AddField(
            model_name='group',
            name='invitation_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Hombre'), ('FEMALE', 'Mujer')], default='MALE', max_length=10),
        ),
        migrations.AddField(
            model_name='publisher',
            name='is_elder',
            field=models.BooleanField(default=False, verbose_name='Anciano'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='is_ministerial_servant',
            field=models.BooleanField(default=False, verbose_name='Siervo Ministerial'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='is_missionary',
            field=models.BooleanField(default=False, verbose_name='Misionero'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='is_special_pioneer',
            field=models.BooleanField(default=False, verbose_name='Precursor Especial'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='spiritual_hope',
            field=models.CharField(choices=[('OTHER_SHEEP', 'Otras Ovejas'), ('ANOINTED', 'Ungido')], default='OTHER_SHEEP', max_length=15),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='is_regular_pioneer',
            field=models.BooleanField(default=False, help_text='Check if the publisher is a Regular Pioneer.', verbose_name='Precursor Regular'),
        ),
    ]
