# Generated by Django 5.0.14 on 2026-02-08 19:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_group_invitation_active_group_invitation_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='invitation_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
