# Generated by Django 5.0.14 on 2026-02-08 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('organization', '0002_congregation_group_congregation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='congregation',
            field=models.ForeignKey(blank=True, help_text='Congregación a la que pertenece este usuario.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='organization.congregation'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CONG_ADMIN', 'Administrador de Congregación'), ('GROUP_ADMIN', 'Administrador de Grupo'), ('VIEWER', 'Visualizador')], default='GROUP_ADMIN', help_text='Nivel de acceso del usuario.', max_length=20),
        ),
    ]
