# Generated by Django 5.0.14 on 2026-02-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_congregation_user_role'),
        ('organization', '0003_group_invitation_active_group_invitation_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='user',
            name='groups_managed',
            field=models.ManyToManyField(blank=True, related_name='managers', to='organization.group', verbose_name='Grupos Administrados (Solo Group Admin)'),
        ),
    ]
