# Generated by Django 5.0.14 on 2026-02-08 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., '2024-2025'", max_length=20)),
                ('start_date', models.DateField(help_text='Usually September 1st.')),
                ('end_date', models.DateField(help_text='Usually August 31st.')),
                ('is_current', models.BooleanField(default=False, help_text='Only one year should be current.')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('participation', models.BooleanField(default=False, help_text='Did the publisher share in the ministry?')),
                ('bible_studies', models.PositiveIntegerField(default=0, help_text='Number of different Bible studies conducted.')),
                ('auxiliary_pioneer', models.BooleanField(default=False, help_text='Check if served as Auxiliary Pioneer this month.')),
                ('hours', models.PositiveIntegerField(blank=True, default=0, help_text='Hours spent in field service (if applicable).', null=True)),
                ('remarks', models.TextField(blank=True, help_text='Any additional notes.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted by Publisher'), ('APPROVED', 'Confirmed by Admin')], default='PENDING', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='organization.publisher')),
            ],
            options={
                'verbose_name': 'Monthly Report',
                'verbose_name_plural': 'Monthly Reports',
                'ordering': ['-month'],
                'unique_together': {('publisher', 'month')},
            },
        ),
    ]
