# Generated by Django 5.0.14 on 2026-02-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='submitted_by',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SUBADMIN', 'Subadmin'), ('PUBLISHER', 'Publisher')], default='ADMIN', max_length=20),
        ),
    ]
